---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 2m30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/dev
  prune: true
