---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-namespace
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-k8s-stack
  path: "./catalog/cert-manager/namespace"
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m0s
  dependsOn:
    - name: cert-manager-namespace
  sourceRef:
    kind: GitRepository
    name: flux-k8s-stack
  path: "./catalog/cert-manager"
  prune: true
  wait: true
  patches:
    - patch: |
        - op: add
          path: /spec/values/serviceAccount
          value:
            annotations:
              iam.gke.io/gcp-service-account: service-account@mail.com
      target:
        kind: HelmRelease
        name: cert-manager
        namespace: cert-manager
