---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-operator
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: arldka
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
