---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kiali
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-k8s-stack
  path: "./catalog/istio-stack/kiali"
  dependsOn:
    # istio system is a hard dependency
    - name: istio-system
      namespace: flux-system
    # The prometheus-operator is required for visualization
    - name: prometheus-operator
      namespace: monitoring
  prune: true
  wait: true
  healthChecks:
    - kind: Deployment
      name: kiali
      namespace: istio-system
